events {}

http {
  server {
    listen 80;

    # Frontend (static site) is served by the `frontend` container.
    # NGINX acts as a single entrypoint and reverse proxy.
    location / {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_redirect off;

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;

      proxy_pass http://frontend:8080;
    }

    location /api/ {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_redirect off;

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_set_header X-Real-IP $remote_addr; # If you don’t care about logging or using the real client IP in Flask, you can omit this line.

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';

      proxy_pass http://api:5000;
    }

    # location = /dispatcher {
    #   return 301 /dispatcher/;
    # }

    location /dispatcher/ {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_redirect off;

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';

      # Strip /dispatcher prefix before sending to alert-dispatcher.
      proxy_pass http://alert-dispatcher:5002/;
    }
  }
}
